# Generated by Django 3.1.1 on 2020-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Table number'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('table', 'customer', 'booking_date')},
        ),
    ]
