# Generated by Django 3.1.1 on 2020-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rest', '0002_auto_20200911_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Number of seats'),
        ),
    ]
