# Generated by Django 3.1.1 on 2020-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rest', '0003_auto_20200911_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.PositiveIntegerField(default=0, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.PositiveIntegerField(default=0, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='table',
            name='size_x',
            field=models.PositiveIntegerField(default=1, verbose_name='Size X in %'),
        ),
        migrations.AddField(
            model_name='table',
            name='size_y',
            field=models.PositiveIntegerField(default=2, verbose_name='Size Y in %'),
        ),
    ]
