# Generated by Django 3.1.1 on 2020-09-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_rest', '0004_auto_20200911_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
